steps:
    run:
        image: codeberg.org/sentryshot/sentryshot-ci:v0.3.0
        commands: "nix-shell /shell.nix --command 'npm install && ./misc/make.sh ci'"
        when:
            event: [push, pull_request, tag]

    build-x86_64:
        image: codeberg.org/sentryshot/sentryshot-build-x86_64:v0.3.0
        commands: "nix-shell /shell.nix --command './misc/make.sh build-target x86_64'"
        when:
            event: [tag]
    build-aarch64:
        image: codeberg.org/sentryshot/sentryshot-build-aarch64:v0.3.0
        commands: "nix-shell /shell.nix --command './target/x86_64-unknown-linux-gnu/debug/make build-target aarch64'"
        when:
            event: [tag]

    tarball:
        image: busybox:1.36
        commands: |
            tag="${CI_COMMIT_TAG}"
            tar -czvf "./build/sentryshot-$tag-x86_64.tar.gz" -C "./build/x86_64" .
            tar -czvf "./build/sentryshot-$tag-aarch64.tar.gz" -C "./build/aarch64" .
            ls ./build

            awk '/^## / { if (p) { exit }; if ($2 == "`${CI_COMMIT_TAG}`") { p=1; next } } p && NF' "./misc/CHANGELOG.md" > release-notes.txt
            cat ./release-notes.txt

            ./misc/utils.sh download-debian-libusb
        when:
            event: [tag]

    docker:
        image: woodpeckerci/plugin-docker-buildx:6.0.3
        settings:
            platforms: linux/amd64,linux/arm64
            repo: codeberg.org/sentryshot/sentryshot
            registry: codeberg.org
            dockerfile: "./misc/Dockerfile"
            tags: ["${CI_COMMIT_TAG}", "latest"]
            username: "Curid"
            password:
                from_secret: cb_token
        when:
            event: [tag]

    release:
        image: woodpeckerci/plugin-gitea-release
        settings:
            base_url: https://codeberg.org
            files:
                - "./build/sentryshot-v*"
            api_key:
                from_secret: cb_token
            target: main
            note: "./release-notes.txt"
            title: "release ${CI_COMMIT_TAG}"
        when:
            event: [tag]
