[package]
name = "csv"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "csv"
path = "csv.rs"
doctest = false

[dependencies]
serde.workspace=true

[dev-dependencies]
pretty_assertions.workspace = true
test-case.workspace = true
