[package]
name = "rust-embed"
version = "6.4.2"
edition.workspace = true
rust-version.workspace = true

[lib]
name = "rust_embed"
path = "embed.rs"
doctest = false

[dependencies]
rust-embed-impl.path = "./impl"
rust-embed-utils.path = "./utils"

